version: '3.3'

services:
  frontend:
    build: .
    ports:
      - "3001:3001"
    network_mode: "host"  # Use host networking
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
