version: '3.3'
services:
  serverside:
    build: ./serverside
    ports:
      - "5000:5000"
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set a strong password for root
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: root  # Set a strong password for the user
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root  # Same password as above
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"

  clientside:
    build: ./clientside
    ports:
      - "3001:3001"
    #network_mode: "host"  # Use host networking
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
