name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Change this to your default branch if necessary
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Backend (Laravel) Setup
      - name: Set up PHP
        uses: actions/setup-php@v2
        with:
          php-version: "8.0" # Use the version compatible with your Laravel project
          extensions: mbstring, xml, bcmath, sqlite3, curl

      - name: Install Composer dependencies
        run: |
          cd backend
          composer install --no-interaction --prefer-dist

      - name: Run Laravel migrations
        run: |
          cd backend
          php artisan migrate --force

      - name: Run Laravel tests
        run: |
          cd backend
          php artisan test

      # Frontend (React) Setup
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Use the version compatible with your React project

      - name: Install npm dependencies
        run: |
          cd frontend
          npm install

      - name: Run React tests
        run: |
          cd frontend
          npm test -- --watchAll=false

      - name: Build React project
        run: |
          cd frontend
          npm run build

      # Deployment step (customize as needed)
      - name: Deploy
        run: |
          echo "Deploying your application..."
          # Add your deployment commands here, e.g., FTP, AWS S3, Heroku, etc.
